apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
    exec: "false"
  namespace: test-validate
spec:
  containers:
    - name: nginx
      image: nginx

# kubectl apply -f validate/exec-forbiden/resource.yaml
# kubectl -n test-validate exec nginx -it -- sh