apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
    exec: "false"
  namespace: test-generate-event
spec:
  containers:
    - name: nginx
      image: nginx

# kubectl apply -f generate/add-event-when-pod-is-exec/resource.yaml  
# kubectl -n test-generate-event exec nginx -it -- sh
# kubectl get events -n test-generate-event
