apiVersion: v1
kind: Pod
metadata:
  name: test-allowed-repo-bad
  namespace: allowed-repo
spec:
  containers:
  - image: corp.reg.com/test-verify-image:signed
    name: test-allowed-repo

# kubectl apply -f validate/allowed-image-repository/bad-resource.yaml --dry-run=server