apiVersion: v1
kind: Pod
metadata:
  name: test-allowed-repo
  namespace: allowed-repo
spec:
  containers:
  - image: myknownimage
    name: test-image

# kubectl apply -f validate/allowed-image-repository/good-resource.yaml --dry-run=server