apiVersion: v1
kind: Pod
metadata:
  name: test-allowed-repo
  namespace: allowed-repo
spec:
  containers:
  - image: myknownimage
    name: myknownimage

# kubectl apply -f validate/allowed-image-repository/good-resource.yaml