apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
  namespace: notary-verify-attestation
spec:
  containers:
  - image: ghcr.io/vishal-chdhry/notary-test:v1
    name: test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}